apiVersion: v1
kind: Namespace
metadata:
  name: k8s-event-logger
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: k8s-event-logger
  namespace: k8s-event-logger
spec:
  interval: 24h
  url: https://charts.deliveryhero.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: k8s-event-logger
  namespace: k8s-event-logger
spec:
  chart:
    spec:
      chart: k8s-event-logger
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-event-logger
      version: 1.1.6
  interval: 24h
  releaseName: k8s-event-logger
  timeout: 15m
  values:
  containerName: k8s-event-logger
  image:
    repository: maxrocketinternet/k8s-event-logger
    pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi