apiVersion: v1
kind: Namespace
metadata:
  name: siglens

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: siglens
  namespace: siglens
spec:
  interval: 24h
  url: https://siglens.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: siglens
  namespace: siglens
spec:
  chart:
    spec:
      chart: siglens
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: siglens
      version: 0.1.3
  interval: 24h
  releaseName: siglens
  timeout: 15m
  values:
    siglens:
      image:
        repository: siglens/siglens
        pullPolicy: Always
        tag: latest