apiVersion: v1
kind: Namespace
metadata:
  name: siglens
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: siglens-git-repo
  namespace: siglens
spec:
  interval: 1m
  url: https://github.com/wussh/siglens-charts.git
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: siglens-release
  namespace: siglens
spec:
  chart:
    spec:
      chart: siglens/siglens-charts
      sourceRef:
        kind: GitRepository
        name: siglens-git-repo
  interval: 24h
  releaseName: siglens
  timeout: 15m
  values:
    siglens:
      image:
        repository: siglens/siglens
        pullPolicy: Always
        tag: latest
