apiVersion: v1
kind: Namespace
metadata:
  name: siglens
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: siglens
  namespace: siglens
spec:
  interval: 1m
  url: https://github.com/wussh/siglens-charts
  branch: main
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: siglens
  namespace: siglens
spec:
  chart: ./charts/siglens
  sourceRef:
    kind: GitRepository
    name: siglens-git-repo
    namespace: siglens
  interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: siglens
  namespace: siglens
spec:
  chart:
    spec:
      chart: siglenss
      sourceRef:
        kind: GitRepository
        name: siglens
        namespace: siglens
  interval: 24h
  releaseName: siglens
  timeout: 15m
  values:
    siglens:
      image:
        repository: siglens/siglens
        pullPolicy: Always
        tag: latest