apiVersion: v1
kind: Namespace
metadata:
  name: app-test-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-1
  namespace: app-test-1
  labels:
    app: app-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test-1
  template:
    metadata:
      labels:
        app: app-test-1
    spec:
      containers:
      - name: app-test-1
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-test-1
  namespace: app-test-1
  labels:
    app: app-test-1
spec:
  selector:
    app: app-test-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-test-1-config
  namespace: app-test-1
data:
  key: value
